In [4]:
import tensorflow as tf
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.
  Attempting uninstall: zipp
    Found existing installation: zipp 3.4.1
    Uninstalling zipp-3.4.1:
      Successfully uninstalled zipp-3.4.1
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 3.10.0
    Uninstalling importlib-metadata-3.10.0:
      Successfully uninstalled importlib-metadata-3.10.0


In [5]:
df=pd.read_csv('DatosAzcapo.txt',sep=',',header=None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52179 entries, 0 to 52178
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       52179 non-null  object 
 1   1       52179 non-null  object 
 2   2       52179 non-null  float64
 3   3       52179 non-null  float64
 4   4       52179 non-null  float64
 5   5       52179 non-null  float64
 6   6       52179 non-null  float64
 7   7       52179 non-null  float64
 8   8       52179 non-null  float64
 9   9       52179 non-null  float64
 10  10      52179 non-null  float64
 11  11      52179 non-null  float64
 12  12      52179 non-null  float64
dtypes: float64(11), object(2)
memory usage: 5.2+ MB


In [7]:
df.head()

0                     1          2          3   \
0  4/4/2024 12:00:00 AM   4/4/2024 6:00:00 AM  28.692070  14.742066   
1  4/4/2024 12:01:00 AM   4/4/2024 6:01:00 AM  32.022658  14.771019   
2  4/4/2024 12:02:00 AM   4/4/2024 6:02:00 AM  32.219123  14.717249   
3  4/4/2024 12:03:00 AM   4/4/2024 6:03:00 AM  31.586301  14.659344   
4  4/4/2024 12:04:00 AM   4/4/2024 6:04:00 AM  32.534500  14.676922   

          4          5          6          7          8          9   \
0  13.950004  23.128830  19.350910  77.827011  28.035599  25.874756   
1  17.251640  23.148970  19.340763  77.817986  27.919699  25.910034   
2  17.501873  23.169109  19.335342  77.820869  27.938000  25.910950   
3  16.926957  23.169109  19.330561  77.814812  27.956299  25.925995   
4  17.857577  23.199320  19.308531  77.830132  27.956299  25.948059   

          10         11        12  
0  33.960640  11.665325  5.025064  
1  33.966431  11.671605  5.068029  
2  33.988586  11.663702  5.003208  
3  33.997185  11.670901  4.931069  
4  34.013283  11.678738  5.000206

In [8]:
df['fechas']=pd.to_datetime(df[0])
df=df.set_index('fechas')

<ipython-input-8-f5f18913dd5c>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['fechas']=pd.to_datetime(df[0])


In [9]:
PM10=df[2]
PM25=df[3]
PMmix=df[4]
Temp=df[6]
Pres=df[7]
RH=df[8]

In [10]:
variable=['$PM_{10}$','$PM_{25}$','$PM_{mix}$','T','P','RH',]
colors=['black','green','red','blue','orange','brown']

In [11]:
Data_in=np.column_stack([Temp,Pres,RH])
Data_out=np.column_stack([PM25])
print(Data_in)
print(len(Data_in))
print(len(Data_out))



[[19.35091019 77.82701111 28.03559875]
 [19.34076309 77.81798553 27.91969872]
 [19.33534241 77.82086945 27.93799973]
 ...
 [27.89101791 78.05047607 26.26659966]
 [27.69476509 78.07154846 25.30279922]
 [27.57023621 78.05378723 24.47929955]]
52179
52179


In [13]:
Data_out.shape[1]

1

In [14]:
#Crear el modelo de TensorFlow
#Definir el modelo secuencial

model=tf.keras.Sequential([
    tf.keras.layers.Dense(3,activation='linear',input_shape=(Data_in.shape[1],)),
    tf.keras.layers.Dense(1,activation='linear')
])

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 12        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 16 (64.00 Byte)
Trainable params: 16 (64.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
from sklearn.model_selection import train_test_split
X_train,y_train,y_test=train_test_split(Data_in,Data_out,test_size=0.2,random_state=42)

ValueError: too many values to unpack (expected 3)